import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  aiOutputLanguage: Language;
  setAiOutputLanguage: (lang: Language) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

// Translation dictionary with Spanish and English
const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.projects': 'Mis Proyectos',
    'nav.signout': 'Cerrar sesión',
    'nav.title': 'GTM Factory',
    
    // Hero Section
    'hero.headline.line1': '¿Tirando presupuesto publicitario en especulaciones?',
    'hero.headline.line2': 'Sabe exactamente quién compra y por qué.',
    'hero.headline.line3': 'En minutos, no meses.',
    'hero.button.run': 'Ejecutar Análisis',
    'hero.placeholder.url': 'https://tuwebsite.com',
    'hero.placeholder.product': '¿Qué vendes o proporcionas? (ej. "Ayudamos a empresas B2B SaaS...")',
    'hero.advanced': 'Añadir Contexto, Competidores y Documentos (Opcional)',
    'hero.context.label': 'Contexto Adicional',
    'hero.context.placeholder': 'Cualquier contexto específico, objetivos o información sobre tu negocio...',
    'hero.competitors.label': 'Competidores Conocidos',
    'hero.competitors.placeholder': 'competidor1.com, competidor2.com...',
    'hero.vision.label': 'Visión',
    'hero.vision.placeholder': 'Tu visión...',
    'hero.mission.label': 'Misión',
    'hero.mission.placeholder': 'Tu misión...',
    'hero.values.label': 'Valores',
    'hero.values.placeholder': 'Tus valores fundamentales...',
    'hero.docs.label': 'Documentos de Negocio',
    'hero.docs.upload': 'Click para subir',
    'hero.docs.drag': 'o arrastra y suelta',
    'hero.docs.types': 'PDF, Word, PowerPoint, Excel (máx 20MB cada uno)',
    'hero.docs.uploaded': 'Documentos subidos:',
    'hero.docs.placeholder': 'O pega cualquier información adicional aquí...',
    'hero.docs.help': 'Sube documentos que proporcionen contexto sobre tu negocio, producto o mercado objetivo',
    'hero.optional': 'Opcional: Conecta datos más tarde para validación y aprendizaje',
    'hero.how': '¿Cómo lo sabemos?',
    'hero.method': 'Sin conjeturas. <strong>Leemos + Referencias Cruzadas + Verificamos</strong>',
    'hero.ai.language': 'Idioma de Salida de IA',
    
    // Status & System
    'status.theoretical': 'Teórico',
    'status.partial': 'Parcial',
    'status.validated': 'Validado',
    'status.stale': 'Obsoleto',
    'status.dialog.title': '¿Qué es un Sistema Vivo?',
    'status.dialog.subtitle': 'Un sistema de análisis de mercado que se mantiene actualizado en tiempo real',
    'status.dialog.description': 'Un sistema de análisis de mercado que se mantiene actualizado en tiempo real conectándose a tus campañas y plataformas de venta.',
    'status.dialog.how': 'CÓMO FUNCIONA:',
    'status.dialog.step1': 'Hipótesis Inicial (IA)',
    'status.dialog.step2': 'Lanzas Experimentos',
    'status.dialog.step3': 'Conectas Plataformas (Meta, Google, etc.)',
    'status.dialog.step4': 'Sistema Valida con Datos Reales',
    'status.dialog.step5': 'Ajusta Automáticamente los Insights',
    'status.dialog.benefits': 'BENEFICIOS:',
    'status.dialog.benefit1': 'Insights basados en TU mercado real',
    'status.dialog.benefit2': 'Decisiones guiadas por datos frescos',
    'status.dialog.benefit3': 'Evita sesgos de "teoría sin validar"',
    'status.dialog.benefit4': 'Aprende continuamente de tus campañas',
    'status.dialog.coming': 'PRÓXIMAMENTE:',
    'status.dialog.platforms': 'Podrás conectar Meta Ads, Google Ads, Amazon Ads, TikTok, Shopify, Email Marketing y más.',
    'status.theoretical.short': 'Datos teóricos sin validar',
    'status.theoretical.detail': 'Estos datos son hipótesis generadas por IA sin validar todavía con datos de mercado.',
    'status.theoretical.soon': 'Próximamente podrás conectar: Meta Ads, Google Ads, Amazon Ads y más',
    
    // Notices
    'notice.theoretical.offer': 'Datos teóricos basados en fórmula de Hormozi. Se validarán con datos reales de campañas.',
    'notice.theoretical.disc': 'Perfiles teóricos según modelo DISC. Se ajustarán con datos de engagement real.',
    'notice.theoretical.channel': 'Análisis teórico. El ranking se actualizará con métricas reales de campañas.',
    'notice.theoretical.persona': 'Perfil basado en análisis de mercado. Se refinará con comportamiento real.',
    'notice.theoretical.validation': 'Experimentos listos. Los resultados se sincronizarán automáticamente al conectar plataformas.',
    'notice.partial.confidence': 'Confianza:',
    'notice.partial.connected': 'Conectado:',
    'notice.stale': 'Datos desactualizados. Lanza nuevos tests para mantener insights frescos.',
    'notice.validated.confidence': 'Confianza:',
    'notice.validated.freshness': 'Freshness:',
    
    // Components
    'buyerpersona.title': 'Buyer Persona',
    'buyerpersona.objections': 'Posibles Objeciones',
    'buyerpersona.objections.source.competitor': 'Ventaja competidora',
    'buyerpersona.objections.source.gap': 'Brecha de mercado',
    'buyerpersona.objections.source.price': 'Precio',
    'buyerpersona.objections.source.trust': 'Barrera de confianza',
    'offer.title': 'Fábrica de ofertas',
    'offer.subtitle': 'Basado en la ecuación de valor de Hormozi',
    'offer.inputs': 'Buyer Persona + Gaps + Características del Producto',
    'offer.value': 'Valor percibido',
    'offer.numerator': 'Numerador',
    'offer.numerator.detail': 'Sueño × Probabilidad',
    'offer.denominator': 'Denominador',
    'offer.denominator.detail': 'Tiempo × Esfuerzo',
    'disc.title': 'Traductor DISC',
    'disc.subtitle': 'Adapta ofertas según personalidad del comprador (Tomas Erikson)',
    'disc.inputs': 'Ofertas + Perfil del Buyer + 4 Estilos DISC',
    'disc.what': '¿Qué es DISC?',
    'disc.description': 'Las personas toman decisiones de compra de formas diferentes. DISC divide a los compradores en 4 tipos según su personalidad:',
    'disc.red': 'Rojo (Dominante)',
    'disc.red.desc': 'Quiere resultados rápidos y directos. Dale datos y beneficios claros.',
    'disc.yellow': 'Amarillo (Influyente)',
    'disc.yellow.desc': 'Quiere sentirse parte de algo. Dale comunidad y experiencias.',
    'disc.green': 'Verde (Estable)',
    'disc.green.desc': 'Necesita confianza y seguridad. Dale garantías y apoyo continuo.',
    'disc.blue': 'Azul (Analítico)',
    'disc.blue.desc': 'Quiere detalles y pruebas. Dale especificaciones y certificaciones.',
    'disc.table.color': 'Color',
    'disc.table.copy': 'Copy',
    'disc.table.channel': 'Canal',
    'disc.table.purpose': 'Propósito',
    
    // Phases
    'phase.1.name': 'Mercado',
    'phase.1.tooltip': 'Análisis profundo de tu web, producto, competidores y oportunidades de mercado',
    'phase.1.title': 'Analizando tu website y el mercado',
    'phase.2.name': 'Buyer',
    'phase.2.tooltip': 'Definición del cliente ideal basado en el mercado real y tu producto',
    'phase.2.title': 'Creando tu Buyer Persona ideal',
    'phase.3.name': 'Ofertas',
    'phase.3.tooltip': 'Ofertas de alto valor usando la ecuación de Hormozi para cada necesidad',
    'phase.3.title': 'Diseñando ofertas de alto valor',
    'phase.4.name': 'DISC',
    'phase.4.tooltip': 'Traducción a 4 lenguajes emocionales: Rojo, Amarillo, Verde y Azul',
    'phase.4.title': 'Traduciendo a los 4 lenguajes DISC',
    'phase.5.name': 'Triggers',
    'phase.5.tooltip': 'Disparadores emocionales que activan la decisión de compra',
    'phase.5.title': 'Generando disparadores emocionales',
    'phase.6.name': 'Validación',
    'phase.6.tooltip': 'Mapa de hipótesis testeables por canal con KPIs y siguiente acción',
    'phase.6.title': 'Creando tu mapa de validación',
    
    // Product components
    'product.nucleus.title': 'Producto',
    'product.nucleus.inputs': 'Problemas + Soluciones + Valor Único',
    'product.nucleus.problems': 'Problemas que resuelve:',
    'product.nucleus.gaps': 'Gaps que puede cubrir:',
    'product.nucleus.value': 'Valor único:',
    'product.understanding.title': 'Comprensión Profunda del Producto',
    'product.understanding.inputs': 'Contenido Web + Tu Descripción + Contexto de Mercado',
    'product.understanding.problems': 'Problemas Resueltos',
    'product.understanding.utility': 'Utilidad y Transformación',
    'product.understanding.value': 'Propuesta de Valor',
    'product.understanding.positioning': 'Posicionamiento en el Mercado',
    'product.understanding.gaps': 'Gaps y Oportunidades del Mercado',
    'product.metrics.title': 'Métricas del Producto',
    'product.positioning.title': 'Mapa de mercado',
    'product.positioning.subtitle': 'Posicionamiento frente a competidores',
    'product.positioning.inputs': 'Tu Producto + Competidores + Gaps del Mercado',
    
    // Validation & Channel
    'validation.title': 'Variaciones Creativas',
    'validation.subtitle': 'variaciones listas para probar • Formato Efecto → Causa',
    'validation.filter.disc': 'Todos DISC',
    'validation.filter.channels': 'Todos Canales',
    'validation.filter.all': 'Todos los perfiles',
    'validation.filter.channels.all': 'Todos los canales',
    'validation.details': 'Ver detalles',
    'validation.state': 'Estado:',
    'validation.effect': 'EFECTO (Lo que validamos):',
    'validation.cause': 'CAUSA (Por qué lo hacemos):',
    'validation.copy': 'Copy:',
    'validation.visual': 'Sugerencia Visual:',
    'validation.reasoning': 'Ver razonamiento estratégico',
    'validation.connect': 'Conectar',
    'channel.title': 'Canal Recomendado:',
    'channel.native': 'Canal Nativo - Audiencia Caliente',
    'channel.subtitle': 'Basado en tu buyer persona, presupuesto y gap de mercado',
    'channel.score': 'Puntuación de viabilidad',
    'channel.advantages': 'Ventajas',
    'channel.considerations': 'Consideraciones',
    'channel.cpl': 'CPL Estimado',
    'channel.time': 'Tiempo a Resultados',
    'channel.budget': 'Presupuesto Recomendado',
    'channel.why': 'POR QUÉ ESTE CANAL:',
    'channel.options': 'Opciones Disponibles en',
    'channel.ads': 'Tipos de Anuncios:',
    'channel.organic': 'Posicionamiento Orgánico:',
    'channel.split': 'Distribución de Presupuesto Recomendada:',
    'channel.comparative': 'Comparativa de Canales',
    'channel.comparative.subtitle': 'Puntuación de viabilidad por canal basada en múltiples factores',
    'channel.ranking': 'Ranking de Alternativas',
    'channel.ranking.subtitle': 'Otras opciones viables ordenadas por puntuación',
    
    // Budget
    'budget.title': 'Define tu presupuesto de campaña',
    'budget.subtitle': 'Esto nos ayudará a recomendar el canal más óptimo para tu estrategia',
    'budget.level': 'Nivel de esfuerzo económico',
    'budget.level.nulo': 'Nulo',
    'budget.level.bajo': 'Bajo',
    'budget.level.medio': 'Medio',
    'budget.level.medioalto': 'Medio-Alto',
    'budget.level.alto': 'Alto',
    'budget.level.maximo': 'Máximo',
    'budget.selected': 'Nivel seleccionado',
    'budget.range.nulo': 'Sin presupuesto disponible',
    'budget.range.bajo': '€500 - €2,000 /mes',
    'budget.range.medio': '€2,000 - €10,000 /mes',
    'budget.range.medioalto': '€10,000 - €30,000 /mes',
    'budget.range.alto': '€30,000 - €100,000 /mes',
    'budget.range.maximo': '€100,000+ /mes',
    'budget.amount': 'Presupuesto estimado (editable)',
    'budget.editable': 'Puedes modificar esta cifra según tu presupuesto real',
    'budget.continue': 'Continuar análisis de canal',
    'budget.why': '¿Por qué es importante?',
    'budget.why.detail': 'El presupuesto determina qué canales son viables para tu estrategia. Un presupuesto bajo puede favorecer canales orgánicos, mientras que uno alto permite experimentar con múltiples canales de pago.',
    
    // Auth & Signup
    'auth.title': 'GTM Factory',
    'auth.subtitle': 'Inicia sesión para acceder a tu análisis de marketing',
    'auth.signin': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.email.placeholder': 'nombre@ejemplo.com',
    'auth.signing': 'Iniciando sesión...',
    'auth.creating': 'Creando cuenta...',
    'auth.create': 'Crear Cuenta',
    'signup.title': 'Desbloquea Fases 4-7',
    'signup.subtitle.signup': 'Regístrate gratis para ver el análisis completo y guardar tus insights',
    'signup.subtitle.signin': 'Inicia sesión para continuar',
    'signup.continue': 'Crear Cuenta y Continuar',
    'signup.signin.continue': 'Iniciar Sesión y Continuar',
    'signup.toggle.signup': '¿Ya tienes cuenta? Inicia sesión',
    'signup.toggle.signin': '¿Nuevo? Regístrate gratis',
    'signup.processing': 'Procesando...',
    'signup.note': 'Tu análisis sigue generándose. Regístrate para verlo completo.',
    
    // Projects
    'projects.title': 'Mis Proyectos',
    'projects.subtitle': 'Accede a todos tus análisis anteriores',
    'projects.back': 'Volver al inicio',
    'projects.empty': 'Aún no tienes proyectos guardados',
    'projects.create': 'Crear primer análisis',
    'projects.view': 'Ver análisis',
    'projects.phases': 'fase',
    'projects.phases.plural': 'fases',
    'projects.completed': 'Completado',
    'projects.phase': 'Fase',
    'projects.updated': 'Actualizado:',
    'projects.recovered': 'Proyectos recuperados',
    'projects.recovered.detail': 'Se han asociado {count} proyecto(s) a tu cuenta',
    
    // Dev Mode
    'dev.title': 'Modo Desarrollo',
    'dev.subtitle': 'Carga datos mock para ver el resultado completo sin gastar créditos',
    'dev.load': 'Cargar Datos Mock',
    
    // Footer
    'footer.copyright': '© 2025 AI GTM Factory. Built on evidence, not opinions.',
  },
  en: {
    // Navigation
    'nav.projects': 'My Projects',
    'nav.signout': 'Sign Out',
    'nav.title': 'GTM Factory',
    
    // Hero Section
    'hero.headline.line1': 'Wasting ad budget on speculations?',
    'hero.headline.line2': 'Know exactly who buys and why.',
    'hero.headline.line3': 'In minutes, not months.',
    'hero.button.run': 'Run Analysis',
    'hero.placeholder.url': 'https://yourwebsite.com',
    'hero.placeholder.product': 'What do you sell or provide? (e.g., "We help B2B SaaS companies...")',
    'hero.advanced': 'Add Context, Competitors & Documents (Optional)',
    'hero.context.label': 'Additional Context',
    'hero.context.placeholder': 'Any specific context, goals, or information about your business...',
    'hero.competitors.label': 'Known Competitors',
    'hero.competitors.placeholder': 'competitor1.com, competitor2.com...',
    'hero.vision.label': 'Vision',
    'hero.vision.placeholder': 'Your vision...',
    'hero.mission.label': 'Mission',
    'hero.mission.placeholder': 'Your mission...',
    'hero.values.label': 'Values',
    'hero.values.placeholder': 'Your core values...',
    'hero.docs.label': 'Business Documents',
    'hero.docs.upload': 'Click to upload',
    'hero.docs.drag': 'or drag and drop',
    'hero.docs.types': 'PDF, Word, PowerPoint, Excel (max 20MB each)',
    'hero.docs.uploaded': 'Uploaded documents:',
    'hero.docs.placeholder': 'Or paste any additional information here...',
    'hero.docs.help': 'Upload documents that provide context about your business, product, or target market',
    'hero.optional': 'Optional: Connect data later for validation & learning',
    'hero.how': 'How do we know?',
    'hero.method': 'No guessing. We <strong>Read + Cross-Reference + Verify</strong>',
    'hero.ai.language': 'AI Output Language',
    
    // Status & System
    'status.theoretical': 'Theoretical',
    'status.partial': 'Partial',
    'status.validated': 'Validated',
    'status.stale': 'Stale',
    'status.dialog.title': 'What is a Live System?',
    'status.dialog.subtitle': 'A market analysis system that stays up-to-date in real-time',
    'status.dialog.description': 'A market analysis system that stays up-to-date in real-time by connecting to your campaigns and sales platforms.',
    'status.dialog.how': 'HOW IT WORKS:',
    'status.dialog.step1': 'Initial Hypothesis (AI)',
    'status.dialog.step2': 'Launch Experiments',
    'status.dialog.step3': 'Connect Platforms (Meta, Google, etc.)',
    'status.dialog.step4': 'System Validates with Real Data',
    'status.dialog.step5': 'Automatically Adjusts Insights',
    'status.dialog.benefits': 'BENEFITS:',
    'status.dialog.benefit1': 'Insights based on YOUR real market',
    'status.dialog.benefit2': 'Decisions guided by fresh data',
    'status.dialog.benefit3': 'Avoid "unvalidated theory" bias',
    'status.dialog.benefit4': 'Continuously learns from your campaigns',
    'status.dialog.coming': 'COMING SOON:',
    'status.dialog.platforms': 'You\'ll be able to connect Meta Ads, Google Ads, Amazon Ads, TikTok, Shopify, Email Marketing, and more.',
    'status.theoretical.short': 'Theoretical unvalidated data',
    'status.theoretical.detail': 'This data is AI-generated hypotheses not yet validated with market data.',
    'status.theoretical.soon': 'Coming soon you\'ll be able to connect: Meta Ads, Google Ads, Amazon Ads and more',
    
    // Notices
    'notice.theoretical.offer': 'Theoretical data based on Hormozi formula. Will be validated with real campaign data.',
    'notice.theoretical.disc': 'Theoretical profiles according to DISC model. Will be adjusted with real engagement data.',
    'notice.theoretical.channel': 'Theoretical analysis. Ranking will be updated with real campaign metrics.',
    'notice.theoretical.persona': 'Profile based on market analysis. Will be refined with real behavior.',
    'notice.theoretical.validation': 'Experiments ready. Results will sync automatically when connecting platforms.',
    'notice.partial.confidence': 'Confidence:',
    'notice.partial.connected': 'Connected:',
    'notice.stale': 'Outdated data. Launch new tests to keep insights fresh.',
    'notice.validated.confidence': 'Confidence:',
    'notice.validated.freshness': 'Freshness:',
    
    // Components
    'buyerpersona.title': 'Buyer Persona',
    'buyerpersona.objections': 'Possible Objections',
    'buyerpersona.objections.source.competitor': 'Competitor advantage',
    'buyerpersona.objections.source.gap': 'Market gap',
    'buyerpersona.objections.source.price': 'Price',
    'buyerpersona.objections.source.trust': 'Trust barrier',
    'offer.title': 'Offer Factory',
    'offer.subtitle': 'Based on Hormozi\'s value equation',
    'offer.inputs': 'Buyer Persona + Gaps + Product Features',
    'offer.value': 'Perceived value',
    'offer.numerator': 'Numerator',
    'offer.numerator.detail': 'Dream × Probability',
    'offer.denominator': 'Denominator',
    'offer.denominator.detail': 'Time × Effort',
    'disc.title': 'DISC Translator',
    'disc.subtitle': 'Adapt offers based on buyer personality (Tomas Erikson)',
    'disc.inputs': 'Offers + Buyer Profile + 4 DISC Styles',
    'disc.what': 'What is DISC?',
    'disc.description': 'People make purchasing decisions differently. DISC divides buyers into 4 types based on their personality:',
    'disc.red': 'Red (Dominant)',
    'disc.red.desc': 'Wants quick and direct results. Give them data and clear benefits.',
    'disc.yellow': 'Yellow (Influencing)',
    'disc.yellow.desc': 'Wants to feel part of something. Give them community and experiences.',
    'disc.green': 'Green (Steady)',
    'disc.green.desc': 'Needs trust and security. Give them guarantees and ongoing support.',
    'disc.blue': 'Blue (Conscientious)',
    'disc.blue.desc': 'Wants details and proof. Give them specifications and certifications.',
    'disc.table.color': 'Color',
    'disc.table.copy': 'Copy',
    'disc.table.channel': 'Channel',
    'disc.table.purpose': 'Purpose',
    
    // Phases
    'phase.1.name': 'Market',
    'phase.1.tooltip': 'Deep analysis of your website, product, competitors and market opportunities',
    'phase.1.title': 'Analyzing your website and the market',
    'phase.2.name': 'Buyer',
    'phase.2.tooltip': 'Definition of ideal customer based on real market and your product',
    'phase.2.title': 'Creating your ideal Buyer Persona',
    'phase.3.name': 'Offers',
    'phase.3.tooltip': 'High-value offers using Hormozi equation for each need',
    'phase.3.title': 'Designing high-value offers',
    'phase.4.name': 'DISC',
    'phase.4.tooltip': 'Translation into 4 emotional languages: Red, Yellow, Green and Blue',
    'phase.4.title': 'Translating to the 4 DISC languages',
    'phase.5.name': 'Triggers',
    'phase.5.tooltip': 'Emotional triggers that activate the purchase decision',
    'phase.5.title': 'Generating emotional triggers',
    'phase.6.name': 'Validation',
    'phase.6.tooltip': 'Map of testable hypotheses by channel with KPIs and next action',
    'phase.6.title': 'Creating your validation map',
    
    // Product components
    'product.nucleus.title': 'Product',
    'product.nucleus.inputs': 'Problems + Solutions + Unique Value',
    'product.nucleus.problems': 'Problems it solves:',
    'product.nucleus.gaps': 'Gaps it can cover:',
    'product.nucleus.value': 'Unique value:',
    'product.understanding.title': 'Deep Product Understanding',
    'product.understanding.inputs': 'Web Content + Your Description + Market Context',
    'product.understanding.problems': 'Problems Solved',
    'product.understanding.utility': 'Utility & Transformation',
    'product.understanding.value': 'Value Proposition',
    'product.understanding.positioning': 'Market Positioning',
    'product.understanding.gaps': 'Market Gaps & Opportunities',
    'product.metrics.title': 'Product Metrics',
    'product.positioning.title': 'Market map',
    'product.positioning.subtitle': 'Positioning vs competitors',
    'product.positioning.inputs': 'Your Product + Competitors + Market Gaps',
    
    // Validation & Channel
    'validation.title': 'Creative Variations',
    'validation.subtitle': 'variations ready to test • Effect → Cause Format',
    'validation.filter.disc': 'All DISC',
    'validation.filter.channels': 'All Channels',
    'validation.filter.all': 'All profiles',
    'validation.filter.channels.all': 'All channels',
    'validation.details': 'View details',
    'validation.state': 'State:',
    'validation.effect': 'EFFECT (What we validate):',
    'validation.cause': 'CAUSE (Why we do it):',
    'validation.copy': 'Copy:',
    'validation.visual': 'Visual Suggestion:',
    'validation.reasoning': 'View strategic reasoning',
    'validation.connect': 'Connect',
    'channel.title': 'Recommended Channel:',
    'channel.native': 'Native Channel - Warm Audience',
    'channel.subtitle': 'Based on your buyer persona, budget and market gap',
    'channel.score': 'Viability score',
    'channel.advantages': 'Advantages',
    'channel.considerations': 'Considerations',
    'channel.cpl': 'Estimated CPL',
    'channel.time': 'Time to Results',
    'channel.budget': 'Recommended Budget',
    'channel.why': 'WHY THIS CHANNEL:',
    'channel.options': 'Available Options on',
    'channel.ads': 'Ad Types:',
    'channel.organic': 'Organic Positioning:',
    'channel.split': 'Recommended Budget Split:',
    'channel.comparative': 'Channel Comparison',
    'channel.comparative.subtitle': 'Viability score per channel based on multiple factors',
    'channel.ranking': 'Alternative Rankings',
    'channel.ranking.subtitle': 'Other viable options ranked by score',
    
    // Budget
    'budget.title': 'Define your campaign budget',
    'budget.subtitle': 'This will help us recommend the most optimal channel for your strategy',
    'budget.level': 'Economic effort level',
    'budget.level.nulo': 'None',
    'budget.level.bajo': 'Low',
    'budget.level.medio': 'Medium',
    'budget.level.medioalto': 'Medium-High',
    'budget.level.alto': 'High',
    'budget.level.maximo': 'Maximum',
    'budget.selected': 'Selected level',
    'budget.range.nulo': 'No budget available',
    'budget.range.bajo': '€500 - €2,000 /month',
    'budget.range.medio': '€2,000 - €10,000 /month',
    'budget.range.medioalto': '€10,000 - €30,000 /month',
    'budget.range.alto': '€30,000 - €100,000 /month',
    'budget.range.maximo': '€100,000+ /month',
    'budget.amount': 'Estimated budget (editable)',
    'budget.editable': 'You can modify this figure according to your actual budget',
    'budget.continue': 'Continue channel analysis',
    'budget.why': 'Why is it important?',
    'budget.why.detail': 'The budget determines which channels are viable for your strategy. A low budget may favor organic channels, while a high one allows experimenting with multiple paid channels.',
    
    // Auth & Signup
    'auth.title': 'GTM Factory',
    'auth.subtitle': 'Sign in to access your marketing analysis',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.email.placeholder': 'name@example.com',
    'auth.signing': 'Signing in...',
    'auth.creating': 'Creating account...',
    'auth.create': 'Create Account',
    'signup.title': 'Unlock Phases 4-7',
    'signup.subtitle.signup': 'Sign up for free to see the complete analysis and save your insights',
    'signup.subtitle.signin': 'Sign in to continue',
    'signup.continue': 'Create Account & Continue',
    'signup.signin.continue': 'Sign In & Continue',
    'signup.toggle.signup': 'Already have an account? Sign in',
    'signup.toggle.signin': 'New? Sign up for free',
    'signup.processing': 'Processing...',
    'signup.note': 'Your analysis is still generating. Sign up to see it complete.',
    
    // Projects
    'projects.title': 'My Projects',
    'projects.subtitle': 'Access all your previous analyses',
    'projects.back': 'Back to home',
    'projects.empty': 'You don\'t have any saved projects yet',
    'projects.create': 'Create first analysis',
    'projects.view': 'View analysis',
    'projects.phases': 'phase',
    'projects.phases.plural': 'phases',
    'projects.completed': 'Completed',
    'projects.phase': 'Phase',
    'projects.updated': 'Updated:',
    'projects.recovered': 'Projects recovered',
    'projects.recovered.detail': '{count} project(s) associated to your account',
    
    // Dev Mode
    'dev.title': 'Development Mode',
    'dev.subtitle': 'Load mock data to see the complete result without spending credits',
    'dev.load': 'Load Mock Data',
    
    // Footer
    'footer.copyright': '© 2025 AI GTM Factory. Built on evidence, not opinions.',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('uiLanguage');
    return (stored === 'es' || stored === 'en') ? stored : 'es';
  });
  
  const [aiOutputLanguage, setAiOutputLanguage] = useState<Language>('es');
  
  const t = (key: string): string => {
    return translations[language][key] || key;
  };
  
  useEffect(() => {
    localStorage.setItem('uiLanguage', language);
  }, [language]);
  
  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      aiOutputLanguage, 
      setAiOutputLanguage 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};
